#!/usr/bin/env node
/**
 * Generate TypeScript types from OpenAPI specification
 * Uses openapi-typescript to generate type-safe API client types
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const OPENAPI_PATH = path.join(__dirname, '../openapi/arinar-v1.yaml');
const OUTPUT_PATH = path.join(__dirname, '../src/generated/api-types.ts');

console.log('🔨 Generating TypeScript types from OpenAPI spec...');

try {
  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_PATH);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Generate types using openapi-typescript
  execSync(
    `npx openapi-typescript ${OPENAPI_PATH} --output ${OUTPUT_PATH}`,
    { stdio: 'inherit' }
  );

  console.log('✅ TypeScript types generated successfully!');
  console.log(`   Output: ${OUTPUT_PATH}`);
  
  // Generate barrel export
  const indexPath = path.join(__dirname, '../src/generated/index.ts');
  const indexContent = `/**
 * Generated API types from OpenAPI specification
 * DO NOT EDIT MANUALLY - Generated by generate-types.js
 */

export * from './api-types';
export * from './event-types';
`;
  
  fs.writeFileSync(indexPath, indexContent, 'utf8');
  console.log('✅ Index file created');

} catch (error) {
  console.error('❌ Type generation failed:', error.message);
  process.exit(1);
}
