import * as api from '@/lib/api';
import styles from './SummaryDisplay.module.css';

interface SummaryDisplayProps {
  summary: api.SummaryResponse;
}

export function SummaryDisplay({ summary }: SummaryDisplayProps) {
  return (
    <div className={styles.container}>
      <h2>Meeting Outputs</h2>
      
      <div className={styles.section}>
        <h3>Summary</h3>
        <p className={styles.summaryText}>{summary.summary}</p>
      </div>

      <div className={styles.section}>
        <h3>Minutes</h3>
        <div className={styles.minutesText}>
          {summary.minutes.split('\n').map((line, idx) => (
            <p key={idx}>{line}</p>
          ))}
        </div>
      </div>

      <div className={styles.section}>
        <h3>Action Items</h3>
        <ul className={styles.actionItems}>
          {summary.action_items.map((item, idx) => (
            <li key={idx} className={styles[`priority-${item.priority}`]}>
              <div className={styles.actionDesc}>{item.description}</div>
              <div className={styles.actionMeta}>
                <span className={styles.owner}>Owner: {item.owner}</span>
                <span className={styles.priority}>Priority: {item.priority}</span>
              </div>
            </li>
          ))}
        </ul>
      </div>

      {summary.model_used && (
        <div className={styles.meta}>
          Generated by {summary.model_used} at {new Date(summary.generated_at).toLocaleString()}
        </div>
      )}
    </div>
  );
}
