"""
Persona Suggester
=================
Given a completed research profile, generates 6 strongly-characterised AI
committee personas specifically matched to the research domain, methodology,
and identified weak areas.

Output per persona:
  name          : realistic academic name + institution
  role          : one of the 6 canonical committee roles
  expertise     : specific expertise area for this research
  focus_area    : the precise angle this person will probe
  system_prompt : full deep system prompt (base canonical + domain specialisation)
  model_id      : model assigned by reasoning mode

The system_prompt is NOT a 120-word snippet — it is a full behavioural
definition built by combining the canonical base prompt (from persona_prompts.py)
with a research-specific specialisation paragraph generated by the LLM.
"""
from __future__ import annotations

import json
import re
from typing import Any, Dict, List, Optional

from ..openrouter_client import OpenRouterClient
from .reasoning_modes import get_model, get_persona_model, ReasoningMode
from .persona_prompts import build_system_prompt, resolve_role, BASE_PROMPTS, ROLE_DISPLAY

COMMITTEE_ROLES = [
    "Advisor",
    "Methodology Professor",
    "Domain Expert",
    "Skeptical Reviewer",
    "Friendly Professor",
    "Independent Reviewer",
]

# ── Persona generation system prompt ────────────────────────────────────────

_SYSTEM = """\
You are an academic review panel designer.

Given a research profile, generate 6 highly specific, realistic AI reviewer personas.

Each persona must be:
  - A real-sounding academic (first name, last name, institution, country)
  - Deeply matched to the research domain, methodology, and identified weak areas
  - Assigned exactly one of the 6 panel roles
  - Likely to ask questions UNIQUE to their role AND to this specific research

Critical requirements:
  - NO two personas may share the same expertise sub-area
  - Each focus_area must identify a SPECIFIC, NON-GENERIC concern tied to the uploaded research
    (e.g., not "evaluate the methodology" but "assess whether the leave-one-out validation
    sufficiently controls for data leakage in the federated setting")
  - specialisation_paragraph must be 80–120 words, written in first person,
    stating EXACTLY what this persona will probe in this specific research,
    what question they will ask first, and what they will never accept without evidence
  - Return ONLY valid JSON — no markdown, no prose

Output format: a JSON array of exactly 6 objects with EXACTLY these keys:
[
  {
    "name":                     "<First Last, Title, Institution>",
    "role":                     "<one of the 6 roles>",
    "expertise":                "<specific sub-area — 1 sentence, research-matched>",
    "focus_area":               "<specific concern in this research — 1 sentence, non-generic>",
    "specialisation_paragraph": "<80-120 words first-person deepening of this role for this research>"
  },
  ...
]
"""

_USER_TEMPLATE = """\
## Research Profile

Research problem:
{research_problem}

Main claim:
{main_claim}

Methodology used:
{methodology}

Dataset / sources:
{dataset_details}

Evidence summary:
{evidence_summary}

Limitations (stated or apparent):
{limitations}

Known weak areas:
{weak_areas}

Possible review questions (already identified):
{possible_questions}

Inferred domain:
{domain_hint}

## Panel Roles to Assign (one per persona — do not reuse)
{roles}

## Instructions
Generate 6 personas, each with a distinct expertise sub-area matched to the research above.
Every focus_area must name a SPECIFIC concern from this research (method, claim, section, or known weak area).
Do NOT use generic academic names. Use culturally diverse, realistic names.
Return a JSON array of exactly 6 objects.
"""


def suggest_personas(
    research_profile: Dict[str, Any],
    openrouter_key: str,
    mode: ReasoningMode = "medium",
) -> List[Dict[str, Any]]:
    """
    Return 6 fully-built reviewer personas for the given research profile.

    Each returned dict has:
      name, role, expertise, focus_area, system_prompt, model_id
    """
    model_id = get_model("persona_suggestion", mode)
    client = OpenRouterClient(api_key=openrouter_key)

    # ── Build user message ────────────────────────────────────────────────
    weak_areas = research_profile.get("weak_areas") or []
    if isinstance(weak_areas, str):
        try:
            weak_areas = json.loads(weak_areas)
        except Exception:
            weak_areas = []
    weak_str = "; ".join(
        w.get("area", str(w)) + (f" ({w.get('reason', '')})" if isinstance(w, dict) and w.get("reason") else "")
        for w in weak_areas
        if w
    ) or "None identified"

    possible_qs = research_profile.get("possible_questions") or []
    if isinstance(possible_qs, list):
        pq_str = "\n".join(f"- {q}" for q in possible_qs[:5])
    else:
        pq_str = str(possible_qs)[:400]

    user_msg = _USER_TEMPLATE.format(
        research_problem  = research_profile.get("research_problem", "Not available")[:300],
        main_claim        = research_profile.get("main_claim",        "Not available")[:300],
        methodology       = research_profile.get("methodology",       "Not available")[:300],
        dataset_details   = research_profile.get("dataset_details",   "Not available")[:200],
        evidence_summary  = research_profile.get("evidence_summary",  "Not available")[:300],
        limitations       = research_profile.get("limitations",       "Not available")[:200],
        weak_areas        = weak_str,
        possible_questions= pq_str,
        domain_hint       = _infer_domain(research_profile),
        roles             = "\n".join(f"{i+1}. {r}" for i, r in enumerate(COMMITTEE_ROLES)),
    )

    response = client.chat_completion(
        model=model_id,
        messages=[
            {"role": "system", "content": _SYSTEM},
            {"role": "user",   "content": user_msg},
        ],
        temperature=0.65,
        max_tokens=3000,
    )

    # ── Parse LLM output ─────────────────────────────────────────────────
    raw = _scrub_json(response["content"])
    try:
        personas: List[Dict] = json.loads(raw)
    except json.JSONDecodeError:
        # Try to extract the first JSON array
        match = re.search(r'\[[\s\S]+\]', raw)
        if match:
            personas = json.loads(match.group(0))
        else:
            raise ValueError(f"Persona suggester returned non-JSON: {raw[:200]}")

    if not isinstance(personas, list):
        personas = personas.get("personas", list(personas.values()))

    # ── Build full system_prompts and attach model_ids ───────────────────
    used_roles: set = set()
    result: List[Dict[str, Any]] = []
    role_queue = list(COMMITTEE_ROLES)

    for p in personas[:6]:
        raw_role = p.get("role", "")
        canonical = resolve_role(raw_role)

        # Prevent duplicate roles
        if canonical in used_roles:
            for fallback in role_queue:
                fc = resolve_role(fallback)
                if fc not in used_roles:
                    canonical = fc
                    break

        used_roles.add(canonical)

        # Decompose name
        full_name_str = p.get("name", f"Dr. Reviewer ({ROLE_DISPLAY.get(canonical, canonical.title())})")
        # Extract just "First Last" for the build call
        name_part = full_name_str.split(",")[0].strip()
        institution = _extract_institution(full_name_str)

        # Build the full deep system_prompt
        full_prompt = build_system_prompt(
            role=canonical,
            persona_name=full_name_str,
            institution=institution,
            expertise=p.get("expertise", f"{canonical.title()} expert"),
            focus_area=p.get("focus_area", "Evaluate research quality"),
            research_profile=research_profile,
        )

        # Append the LLM-generated specialisation paragraph on top of the base
        specialisation = (p.get("specialisation_paragraph") or "").strip()
        if specialisation and len(specialisation) > 40:
            full_prompt = (
                f"[SPECIALISATION FOR THIS RESEARCH SESSION]\n{specialisation}\n\n"
                + full_prompt
            )

        result.append({
            "name":         full_name_str,
            "role":         ROLE_DISPLAY.get(canonical, canonical.title()),
            "expertise":    p.get("expertise", ""),
            "focus_area":   p.get("focus_area", ""),
            "system_prompt": full_prompt,
            "model_id":     get_persona_model(ROLE_DISPLAY.get(canonical, canonical.title()), mode),
        })

    # Fill missing roles if LLM returned fewer than 6
    all_canonicals = [resolve_role(r) for r in COMMITTEE_ROLES]
    for canonical in all_canonicals:
        if canonical not in used_roles:
            display = ROLE_DISPLAY.get(canonical, canonical.title())
            full_prompt = build_system_prompt(
                role=canonical,
                persona_name=f"Dr. Panel Member ({display})",
                institution="Academic Institution",
                expertise=f"{display} expert",
                focus_area="Evaluate research quality from the assigned reviewer lane",
                research_profile=research_profile,
            )
            result.append({
                "name":         f"Dr. Panel Member ({display})",
                "role":         display,
                "expertise":    f"{display} expertise",
                "focus_area":   "Evaluate research quality",
                "system_prompt": full_prompt,
                "model_id":     get_persona_model(display, mode),
            })
            used_roles.add(canonical)

    return result[:6]


# ── Helpers ──────────────────────────────────────────────────────────────────

def _scrub_json(text: str) -> str:
    text = text.strip()
    text = re.sub(r"^```(?:json)?\s*\n?", "", text)
    text = re.sub(r"\n?```\s*$", "", text)
    return text.strip()


def _extract_institution(full_name_str: str) -> str:
    """Try to pull institution from 'First Last, Title, Institution' format."""
    parts = [p.strip() for p in full_name_str.split(",")]
    if len(parts) >= 3:
        return parts[-1]
    if len(parts) == 2:
        return parts[-1]
    return "Academic Institution"


def _infer_domain(profile: Dict) -> str:
    """Guess the research domain from profile keywords."""
    text = " ".join(filter(None, [
        profile.get("research_problem", ""),
        profile.get("methodology", ""),
        profile.get("main_claim", ""),
        profile.get("evidence_summary", ""),
    ])).lower()

    domain_map = [
        (r"machine learning|deep learning|neural|transformer|llm|language model|nlp|bert|gpt",
         "AI / Machine Learning / NLP"),
        (r"federated|differential privacy|secure aggregation|privacy.preserving",
         "Privacy-Preserving ML / Federated Learning"),
        (r"medical|clinical|patient|health|disease|biomedical|eeg|fmri|genomic",
         "Biomedical / Health Informatics"),
        (r"database|query|sql|nosql|graph database|knowledge graph|ontolog",
         "Database Systems / Knowledge Representation"),
        (r"network|distributed|cloud|microservice|kubernetes|edge computing",
         "Distributed Systems / Cloud Computing"),
        (r"vision|image|object detection|segmentation|cnn|video|point cloud",
         "Computer Vision"),
        (r"robot|control|actuator|sensor|autonomous|planning|navigation",
         "Robotics / Autonomous Systems"),
        (r"social|survey|interview|qualitative|grounded theory|thematic",
         "Social Science / HCI Research"),
        (r"blockchain|smart contract|decentralized|web3|consensus",
         "Blockchain / Decentralised Systems"),
        (r"security|attack|vulnerability|encryption|authentication|adversarial",
         "Cybersecurity / Adversarial ML"),
        (r"reinforcement|reward|policy gradient|agent|environment|markov",
         "Reinforcement Learning"),
        (r"graph neural|gnn|knowledge graph|link prediction|node classification",
         "Graph Neural Networks"),
        (r"recommender|collaborative filtering|matrix factorisation|embedding",
         "Recommender Systems"),
        (r"time series|forecasting|anomaly detection|temporal",
         "Time Series Analysis"),
        (r"climate|energy|sustainability|environmental",
         "Environmental / Sustainability Computing"),
    ]

    for pattern, domain in domain_map:
        if re.search(pattern, text):
            return domain
    return "Computer Science / Engineering"
